version: '3.9'

services:
  flask_app:
    container_name: flask_app
    restart: always
    image: testhubdockerlvea/flask_app:latest
    build: ./flask_app
    #ports:
    #  - "8001:8001"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    image: testhubdockerlvea/nginx:latest
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
